{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "8Gu5X-QMe15k"
      },
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install cadquery\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "BulRT_Xie7U_",
        "outputId": "c85bce73-0c35-4da4-b07c-4fc7993ebb6f"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting cadquery\n",
            "  Downloading cadquery-2.5.2-py3-none-any.whl.metadata (16 kB)\n",
            "Collecting cadquery-ocp<7.8,>=7.7.0 (from cadquery)\n",
            "  Downloading cadquery_ocp-7.7.2-cp311-cp311-manylinux_2_35_x86_64.whl.metadata (1.6 kB)\n",
            "Collecting ezdxf (from cadquery)\n",
            "  Downloading ezdxf-1.4.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.8 kB)\n",
            "Collecting multimethod<2.0,>=1.11 (from cadquery)\n",
            "  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)\n",
            "Collecting nlopt<3.0,>=2.9.0 (from cadquery)\n",
            "  Downloading nlopt-2.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)\n",
            "Collecting typish (from cadquery)\n",
            "  Downloading typish-1.9.3-py3-none-any.whl.metadata (7.2 kB)\n",
            "Collecting casadi (from cadquery)\n",
            "  Downloading casadi-3.7.0-cp311-none-manylinux2014_x86_64.whl.metadata (2.2 kB)\n",
            "Collecting path (from cadquery)\n",
            "  Downloading path-17.1.0-py3-none-any.whl.metadata (6.4 kB)\n",
            "Requirement already satisfied: numpy<3,>=2 in /usr/local/lib/python3.11/dist-packages (from nlopt<3.0,>=2.9.0->cadquery) (2.0.2)\n",
            "Requirement already satisfied: pyparsing>=2.0.1 in /usr/local/lib/python3.11/dist-packages (from ezdxf->cadquery) (3.2.3)\n",
            "Requirement already satisfied: typing_extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from ezdxf->cadquery) (4.13.2)\n",
            "Requirement already satisfied: fonttools in /usr/local/lib/python3.11/dist-packages (from ezdxf->cadquery) (4.58.0)\n",
            "Downloading cadquery-2.5.2-py3-none-any.whl (163 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m163.9/163.9 kB\u001b[0m \u001b[31m4.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading cadquery_ocp-7.7.2-cp311-cp311-manylinux_2_35_x86_64.whl (143.0 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m143.0/143.0 MB\u001b[0m \u001b[31m3.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading multimethod-1.12-py3-none-any.whl (10 kB)\n",
            "Downloading nlopt-2.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (436 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m436.8/436.8 kB\u001b[0m \u001b[31m26.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading casadi-3.7.0-cp311-none-manylinux2014_x86_64.whl (77.3 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m77.3/77.3 MB\u001b[0m \u001b[31m10.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading ezdxf-1.4.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.8 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m5.8/5.8 MB\u001b[0m \u001b[31m79.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading path-17.1.0-py3-none-any.whl (23 kB)\n",
            "Downloading typish-1.9.3-py3-none-any.whl (45 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m45.1/45.1 kB\u001b[0m \u001b[31m2.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: typish, cadquery-ocp, path, nlopt, multimethod, ezdxf, casadi, cadquery\n",
            "Successfully installed cadquery-2.5.2 cadquery-ocp-7.7.2 casadi-3.7.0 ezdxf-1.4.2 multimethod-1.12 nlopt-2.9.1 path-17.1.0 typish-1.9.3\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import cadquery as cq\n",
        "\n",
        "# Base block\n",
        "base = cq.Workplane(\"XY\").box(200, 200, 100)\n",
        "\n",
        "# Upper block\n",
        "upper_block_height = 80\n",
        "upper_block = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .box(180, 180, upper_block_height)\n",
        "    .translate((0, 0, 50 + upper_block_height / 2))\n",
        ")\n",
        "\n",
        "upper_block_top_z = 50 + upper_block_height  # 130 mm\n",
        "\n",
        "# Stick properties\n",
        "stick_diameter = 40\n",
        "stick_height = 20\n",
        "\n",
        "# Stick 1 (between upper block and plate)\n",
        "stick1_x = 70\n",
        "stick1 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(stick_diameter / 2)\n",
        "    .extrude(stick_height)\n",
        "    .translate((stick1_x, 0, upper_block_top_z))\n",
        ")\n",
        "\n",
        "# Plate parameters\n",
        "plate_length = 200\n",
        "plate_width = 100\n",
        "plate_height = 20\n",
        "plate_center_x = 150\n",
        "\n",
        "plate_base_z = upper_block_top_z + stick_height  # 150 mm\n",
        "\n",
        "plate = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .ellipse(plate_length / 2, plate_width / 2)\n",
        "    .extrude(plate_height)\n",
        "    .translate((plate_center_x, 0, plate_base_z))\n",
        ")\n",
        "\n",
        "# Stick 2 (on plate surface, 120 mm right from plate right edge)\n",
        "stick2 = (\n",
        "    plate.faces(\">Z\").workplane()\n",
        "    .center(plate_length / 2 + 120, 0)\n",
        "    .circle(stick_diameter / 2)\n",
        "    .extrude(stick_height)\n",
        ")\n",
        "\n",
        "# New block as a plate shape, same size as original plate but height 10 cm (100 mm)\n",
        "new_block_height = 100  # 10 cm height\n",
        "\n",
        "new_block_x = plate_center_x + 120\n",
        "new_block_base_z = plate_base_z + plate_height + stick_height\n",
        "\n",
        "new_block = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .ellipse(plate_length / 2, plate_width / 2)\n",
        "    .extrude(new_block_height)\n",
        "    .translate((\n",
        "        new_block_x,  # aligned with stick2\n",
        "        0,\n",
        "        new_block_base_z  # on top of stick2\n",
        "    ))\n",
        ")\n",
        "\n",
        "# Stick 3 (below right side of the new block)\n",
        "stick3_x = new_block_x + plate_length / 2 - stick_diameter / 2  # right edge adjusted\n",
        "stick3_z = new_block_base_z - stick_height  # right below new block base\n",
        "\n",
        "stick3 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(stick_diameter / 2)\n",
        "    .extrude(stick_height)\n",
        "    .translate((stick3_x, 0, stick3_z))\n",
        ")\n",
        "\n",
        "# Stick 4 (diameter 1 cm) from center top of stick 3 down to floor (z=0)\n",
        "stick4_diameter = 10  # 1 cm = 10 mm\n",
        "\n",
        "stick4_top_z = stick3_z + stick_height  # top of stick3\n",
        "stick4_height = stick4_top_z  # height from stick3 top to floor\n",
        "\n",
        "# Extrude downward a bit longer to ensure it touches floor\n",
        "stick4 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(stick4_diameter / 2)\n",
        "    .extrude(-stick4_height - 1)  # extra 1 mm down\n",
        "    .translate((stick3_x, 0, stick4_top_z))\n",
        ")\n",
        "\n",
        "# Plate at the bottom of stick4 on floor (z=0), same length and width as original plate,\n",
        "# but height is 1/3 of original plate height\n",
        "stick4_bottom_plate_height = plate_height / 3  # ~6.67 mm\n",
        "\n",
        "stick4_bottom_plate = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .ellipse(plate_length / 2, plate_width / 2)\n",
        "    .extrude(stick4_bottom_plate_height)\n",
        "    .translate((stick3_x, 0, 0))  # floor level\n",
        ")\n",
        "\n",
        "# Combine all parts\n",
        "assembly = (\n",
        "    base\n",
        "    .union(upper_block)\n",
        "    .union(stick1)\n",
        "    .union(plate)\n",
        "    .union(stick2)\n",
        "    .union(new_block)\n",
        "    .union(stick3)\n",
        "    .union(stick4)\n",
        "    .union(stick4_bottom_plate)\n",
        ")\n",
        "\n",
        "# Export STL\n",
        "cq.exporters.export(assembly, \"robotic_arm_with_stick4_plate_bottom_thinner.stl\")\n",
        "\n",
        "# Confirm file exists\n",
        "import os\n",
        "print(\"STL exists:\", os.path.exists(\"robotic_arm_with_stick4_plate_bottom_thinner.stl\"))\n",
        "\n",
        "from google.colab import files\n",
        "files.download(\"robotic_arm_with_stick4_plate_bottom_thinner.stl\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "id": "h1aZykC1GqmM",
        "outputId": "c9fdd41e-d21b-428d-a35a-6a8581468162"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "STL exists: True\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "    async function download(id, filename, size) {\n",
              "      if (!google.colab.kernel.accessAllowed) {\n",
              "        return;\n",
              "      }\n",
              "      const div = document.createElement('div');\n",
              "      const label = document.createElement('label');\n",
              "      label.textContent = `Downloading \"${filename}\": `;\n",
              "      div.appendChild(label);\n",
              "      const progress = document.createElement('progress');\n",
              "      progress.max = size;\n",
              "      div.appendChild(progress);\n",
              "      document.body.appendChild(div);\n",
              "\n",
              "      const buffers = [];\n",
              "      let downloaded = 0;\n",
              "\n",
              "      const channel = await google.colab.kernel.comms.open(id);\n",
              "      // Send a message to notify the kernel that we're ready.\n",
              "      channel.send({})\n",
              "\n",
              "      for await (const message of channel.messages) {\n",
              "        // Send a message to notify the kernel that we're ready.\n",
              "        channel.send({})\n",
              "        if (message.buffers) {\n",
              "          for (const buffer of message.buffers) {\n",
              "            buffers.push(buffer);\n",
              "            downloaded += buffer.byteLength;\n",
              "            progress.value = downloaded;\n",
              "          }\n",
              "        }\n",
              "      }\n",
              "      const blob = new Blob(buffers, {type: 'application/binary'});\n",
              "      const a = document.createElement('a');\n",
              "      a.href = window.URL.createObjectURL(blob);\n",
              "      a.download = filename;\n",
              "      div.appendChild(a);\n",
              "      a.click();\n",
              "      div.remove();\n",
              "    }\n",
              "  "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "download(\"download_097d990b-e0b0-468d-8b40-c3f511ccab81\", \"robotic_arm_with_stick4_plate_bottom_thinner.stl\", 221584)"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import cadquery as cq\n",
        "\n",
        "# Base block\n",
        "base = cq.Workplane(\"XY\").box(200, 200, 100)\n",
        "\n",
        "# Upper block\n",
        "upper_block_height = 80\n",
        "upper_block = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .box(180, 180, upper_block_height)\n",
        "    .translate((0, 0, 50 + upper_block_height / 2))\n",
        ")\n",
        "\n",
        "upper_block_top_z = 50 + upper_block_height  # 130 mm\n",
        "\n",
        "# Stick properties\n",
        "stick_diameter = 40\n",
        "stick_height = 20\n",
        "\n",
        "# Stick 1 (between upper block and plate)\n",
        "stick1_x = 70\n",
        "stick1 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(stick_diameter / 2)\n",
        "    .extrude(stick_height)\n",
        "    .translate((stick1_x, 0, upper_block_top_z))\n",
        ")\n",
        "\n",
        "# Plate parameters\n",
        "plate_length = 200\n",
        "plate_width = 100\n",
        "plate_height = 20\n",
        "plate_center_x = 150\n",
        "\n",
        "plate_base_z = upper_block_top_z + stick_height  # 150 mm\n",
        "\n",
        "plate = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .ellipse(plate_length / 2, plate_width / 2)\n",
        "    .extrude(plate_height)\n",
        "    .translate((plate_center_x, 0, plate_base_z))\n",
        ")\n",
        "\n",
        "# Stick 2 (on plate surface, 120 mm right from plate right edge)\n",
        "stick2 = (\n",
        "    plate.faces(\">Z\").workplane()\n",
        "    .center(plate_length / 2 + 120, 0)\n",
        "    .circle(stick_diameter / 2)\n",
        "    .extrude(stick_height)\n",
        ")\n",
        "\n",
        "# New block as a plate shape, same size as original plate but height 10 cm (100 mm)\n",
        "new_block_height = 100  # 10 cm height\n",
        "\n",
        "new_block_x = plate_center_x + 120\n",
        "new_block_base_z = plate_base_z + plate_height + stick_height\n",
        "\n",
        "new_block = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .ellipse(plate_length / 2, plate_width / 2)\n",
        "    .extrude(new_block_height)\n",
        "    .translate((\n",
        "        new_block_x,  # aligned with stick2\n",
        "        0,\n",
        "        new_block_base_z  # on top of stick2\n",
        "    ))\n",
        ")\n",
        "\n",
        "# Stick 3 (below right side of the new block)\n",
        "stick3_x = new_block_x + plate_length / 2 - stick_diameter / 2  # right edge adjusted\n",
        "stick3_z = new_block_base_z - stick_height  # right below new block base\n",
        "\n",
        "stick3 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(stick_diameter / 2)\n",
        "    .extrude(stick_height)\n",
        "    .translate((stick3_x, 0, stick3_z))\n",
        ")\n",
        "\n",
        "# Stick 4 (diameter 1 cm) from center top of stick 3 down to floor (z=0)\n",
        "stick4_diameter = 10  # 1 cm = 10 mm\n",
        "\n",
        "stick4_top_z = stick3_z + stick_height  # top of stick3\n",
        "stick4_height = stick4_top_z  # height from stick3 top to floor\n",
        "\n",
        "# Extrude downward a bit longer to ensure it touches floor\n",
        "stick4 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(stick4_diameter / 2)\n",
        "    .extrude(-stick4_height - 1)  # extra 1 mm down\n",
        "    .translate((stick3_x, 0, stick4_top_z))\n",
        ")\n",
        "\n",
        "# Plate at the bottom of stick4 on floor (z=0), same length and width as original plate,\n",
        "# but height is 1/3 of original plate height\n",
        "stick4_bottom_plate_height = plate_height / 3  # ~6.67 mm\n",
        "\n",
        "stick4_bottom_plate = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .ellipse(plate_length / 2, plate_width / 2)\n",
        "    .extrude(stick4_bottom_plate_height)\n",
        "    .translate((stick3_x, 0, 0))  # floor level\n",
        ")\n",
        "\n",
        "# SEWING MACHINE COMPONENTS\n",
        "# Sewing machine base (positioned to the right of the robotic arm, aligned with stick4 bottom plate)\n",
        "sewing_base_x = stick3_x + 200  # Right side of the robotic arm, further right from stick4\n",
        "sewing_base_width = 120\n",
        "sewing_base_length = 180\n",
        "sewing_base_height = 15\n",
        "\n",
        "sewing_base = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .box(sewing_base_length, sewing_base_width, sewing_base_height)\n",
        "    .translate((sewing_base_x, 0, sewing_base_height / 2))\n",
        ")\n",
        "\n",
        "# Sewing machine body (main housing)\n",
        "sewing_body_height = 80\n",
        "sewing_body_width = 100\n",
        "sewing_body_length = 140\n",
        "\n",
        "sewing_body = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .box(sewing_body_length, sewing_body_width, sewing_body_height)\n",
        "    .translate((sewing_base_x, 0, sewing_base_height + sewing_body_height / 2))\n",
        ")\n",
        "\n",
        "# Sewing machine arm (extends upward and forward)\n",
        "sewing_arm_width = 40\n",
        "sewing_arm_height = 60\n",
        "sewing_arm_length = 100\n",
        "\n",
        "sewing_arm = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .box(sewing_arm_length, sewing_arm_width, sewing_arm_height)\n",
        "    .translate((sewing_base_x + 20, 0, sewing_base_height + sewing_body_height + sewing_arm_height / 2))\n",
        ")\n",
        "\n",
        "# Needle area (small cylinder at the front of the arm) - aligned with transport rail height\n",
        "needle_z_position = transport_rail_height  # Same height as transport rail\n",
        "\n",
        "needle = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(needle_diameter / 2)\n",
        "    .extrude(needle_height)\n",
        "    .translate((sewing_base_x + sewing_arm_length / 2, 0, needle_z_position))\n",
        ")\n",
        "\n",
        "# Spool holder (vertical rod on top)\n",
        "spool_holder_diameter = 6\n",
        "spool_holder_height = 40\n",
        "\n",
        "spool_holder = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(spool_holder_diameter / 2)\n",
        "    .extrude(spool_holder_height)\n",
        "    .translate((sewing_base_x - 30, 20, sewing_base_height + sewing_body_height))\n",
        ")\n",
        "\n",
        "# Thread spool (small cylinder on the holder)\n",
        "spool_diameter = 20\n",
        "spool_height = 15\n",
        "\n",
        "thread_spool = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(spool_diameter / 2)\n",
        "    .extrude(spool_height)\n",
        "    .translate((sewing_base_x - 30, 20, sewing_base_height + sewing_body_height + spool_holder_height))\n",
        ")\n",
        "\n",
        "# Bobbin case (small box under the needle area)\n",
        "bobbin_case_size = 25\n",
        "bobbin_case_height = 10\n",
        "\n",
        "bobbin_case = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .box(bobbin_case_size, bobbin_case_size, bobbin_case_height)\n",
        "    .translate((sewing_base_x + 30, 0, sewing_base_height / 2))\n",
        ")\n",
        "\n",
        "# Control panel (small raised area with buttons)\n",
        "control_panel_width = 60\n",
        "control_panel_length = 40\n",
        "control_panel_height = 8\n",
        "\n",
        "control_panel = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .box(control_panel_length, control_panel_width, control_panel_height)\n",
        "    .translate((sewing_base_x - 20, -20, sewing_base_height + sewing_body_height))\n",
        ")\n",
        "\n",
        "# Small control buttons (cylinders on the control panel)\n",
        "button_diameter = 8\n",
        "button_height = 3\n",
        "\n",
        "button1 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(button_diameter / 2)\n",
        "    .extrude(button_height)\n",
        "    .translate((sewing_base_x - 10, -15, sewing_base_height + sewing_body_height + control_panel_height))\n",
        ")\n",
        "\n",
        "button2 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(button_diameter / 2)\n",
        "    .extrude(button_height)\n",
        "    .translate((sewing_base_x - 30, -15, sewing_base_height + sewing_body_height + control_panel_height))\n",
        ")\n",
        "\n",
        "button3 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(button_diameter / 2)\n",
        "    .extrude(button_height)\n",
        "    .translate((sewing_base_x - 20, -25, sewing_base_height + sewing_body_height + control_panel_height))\n",
        ")\n",
        "\n",
        "# Combine all robotic arm parts\n",
        "robotic_arm = (\n",
        "    base\n",
        "    .union(upper_block)\n",
        "    .union(stick1)\n",
        "    .union(plate)\n",
        "    .union(stick2)\n",
        "    .union(new_block)\n",
        "    .union(stick3)\n",
        "    .union(stick4)\n",
        "    .union(stick4_bottom_plate)\n",
        ")\n",
        "\n",
        "# CONVEYOR/TRANSPORT SYSTEM between stick4 bottom plate and sewing machine\n",
        "# Transport rail/track (connects the bottom plate to sewing machine)\n",
        "transport_rail_start_x = stick3_x + plate_length / 2  # End of bottom plate\n",
        "transport_rail_end_x = sewing_base_x - sewing_base_length / 2  # Start of sewing machine\n",
        "transport_rail_length = transport_rail_end_x - transport_rail_start_x\n",
        "transport_rail_width = 20\n",
        "transport_rail_height = 8\n",
        "\n",
        "transport_rail = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .box(transport_rail_length, transport_rail_width, transport_rail_height)\n",
        "    .translate((transport_rail_start_x + transport_rail_length / 2, 0, transport_rail_height / 2))\n",
        ")\n",
        "\n",
        "# Support pillars for the transport rail\n",
        "pillar_diameter = 15\n",
        "pillar_height = transport_rail_height / 2\n",
        "pillar_spacing = transport_rail_length / 4\n",
        "\n",
        "# Pillar 1\n",
        "pillar1 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(pillar_diameter / 2)\n",
        "    .extrude(pillar_height)\n",
        "    .translate((transport_rail_start_x + pillar_spacing, 0, 0))\n",
        ")\n",
        "\n",
        "# Pillar 2\n",
        "pillar2 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(pillar_diameter / 2)\n",
        "    .extrude(pillar_height)\n",
        "    .translate((transport_rail_start_x + 2 * pillar_spacing, 0, 0))\n",
        ")\n",
        "\n",
        "# Pillar 3\n",
        "pillar3 = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .circle(pillar_diameter / 2)\n",
        "    .extrude(pillar_height)\n",
        "    .translate((transport_rail_start_x + 3 * pillar_spacing, 0, 0))\n",
        ")\n",
        "\n",
        "# Transport cart/platform that moves along the rail\n",
        "cart_width = 40\n",
        "cart_length = 60\n",
        "cart_height = 5\n",
        "\n",
        "transport_cart = (\n",
        "    cq.Workplane(\"XY\")\n",
        "    .box(cart_length, cart_width, cart_height)\n",
        "    .translate((transport_rail_start_x + transport_rail_length / 2, 0, transport_rail_height + cart_height / 2))\n",
        ")\n",
        "sewing_machine = (\n",
        "    sewing_base\n",
        "    .union(sewing_body)\n",
        "    .union(sewing_arm)\n",
        "    .union(needle)\n",
        "    .union(spool_holder)\n",
        "    .union(thread_spool)\n",
        "    .union(bobbin_case)\n",
        "    .union(control_panel)\n",
        "    .union(button1)\n",
        "    .union(button2)\n",
        "    .union(button3)\n",
        ")\n",
        "\n",
        "# Combine everything\n",
        "complete_assembly = robotic_arm.union(sewing_machine)\n",
        "\n",
        "# Export STL\n",
        "cq.exporters.export(complete_assembly, \"robotic_arm_with_sewing_machine.stl\")\n",
        "\n",
        "# Confirm file exists\n",
        "import os\n",
        "print(\"STL exists:\", os.path.exists(\"robotic_arm_with_sewing_machine.stl\"))\n",
        "\n",
        "from google.colab import files\n",
        "files.download(\"robotic_arm_with_sewing_machine.stl\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        },
        "id": "KQO_WdK5r319",
        "outputId": "8f32e790-94fa-44b9-e593-66c72488a9bb"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "STL exists: True\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "    async function download(id, filename, size) {\n",
              "      if (!google.colab.kernel.accessAllowed) {\n",
              "        return;\n",
              "      }\n",
              "      const div = document.createElement('div');\n",
              "      const label = document.createElement('label');\n",
              "      label.textContent = `Downloading \"${filename}\": `;\n",
              "      div.appendChild(label);\n",
              "      const progress = document.createElement('progress');\n",
              "      progress.max = size;\n",
              "      div.appendChild(progress);\n",
              "      document.body.appendChild(div);\n",
              "\n",
              "      const buffers = [];\n",
              "      let downloaded = 0;\n",
              "\n",
              "      const channel = await google.colab.kernel.comms.open(id);\n",
              "      // Send a message to notify the kernel that we're ready.\n",
              "      channel.send({})\n",
              "\n",
              "      for await (const message of channel.messages) {\n",
              "        // Send a message to notify the kernel that we're ready.\n",
              "        channel.send({})\n",
              "        if (message.buffers) {\n",
              "          for (const buffer of message.buffers) {\n",
              "            buffers.push(buffer);\n",
              "            downloaded += buffer.byteLength;\n",
              "            progress.value = downloaded;\n",
              "          }\n",
              "        }\n",
              "      }\n",
              "      const blob = new Blob(buffers, {type: 'application/binary'});\n",
              "      const a = document.createElement('a');\n",
              "      a.href = window.URL.createObjectURL(blob);\n",
              "      a.download = filename;\n",
              "      div.appendChild(a);\n",
              "      a.click();\n",
              "      div.remove();\n",
              "    }\n",
              "  "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "download(\"download_0d69056c-4cb8-47ec-ba26-d32875e29bdc\", \"robotic_arm_with_sewing_machine.stl\", 303484)"
            ]
          },
          "metadata": {}
        }
      ]
    }
  ]
}